### ISSUE TITLE
Daily Journal - Load the given day's page and it's data

### ISSUE THREAD

**Issue by lhuijser** [UOA-SE701-Group3-2021/3Lancers#113]
**Is your feature request related to a problem? Please describe.**
As an end-user, I want to see the current day's journal page and the widgets I put in it so that I can continue to work on this journal entry.

**Describe the solution you'd like**
Implemented functionality of loading a given day's journal page and the data stored in it. Data can be dummy data for this issue, and the date can be hardcoded for this issue as well. No connection to the back-end is necessary for now. 

**Describe alternatives you've considered**
Don't implement this functionality, which would remove a core feature of the product i.e. being able to use the Daily Journal and view it's entries.

**Additional context**
Blocked by #61

**Comment by ambiyu** [comment]
Loading with dummy data added in #150 and integrated with backend in #205.
