### ISSUE TITLE
Hi-fi design of Habit Tracker User Input Menu

### ISSUE THREAD

**Issue by ODE-BOY** [UOA-SE701-Group3-2021/3Lancers#117]
**Is your feature request related to a problem? Please describe.**
As a frontend developer, I want a detailed prototype of the Habit Tracker User Input Menu I'm implementing, so that I can finalise the styling and logic. The user can interact with this Menu to add a new habit or edit an existing habit.

**Describe the solution you'd like**
A hi-fi prototype of the Habit Tracker User Input Menu

**Describe alternatives you've considered**
Start coding right away - would result in conflict further down the road.
Come up with own styling - would stand out from the UI.

**Comment by RawiriHohepa** [comment]
Can you move the additional context to the end of the problem description? Then happy to approve

**Comment by ODE-BOY** [comment]
All done.
