### ISSUE TITLE
Calendar showing up instead of home screen

### ISSUE THREAD

**Issue by maheknangia** [UOA-SE701-Group3-2021/3Lancers#127]
**Describe the bug**
On the Home Screen, the calendar journal shows up instead

**To Reproduce**
1. Clone repository 
2. npm install
3. npm start
4. See calendar journal 

**Expected behavior**
See home screen instead of journal calendar 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JChamberlain28** [comment]
This is because it is rendered in index.js and was merged in that state. I try removing and replacing with <App /> on my local fork but that causes missing dependency errors.

I think this issue blocks a few from progressing as we cannot test our widgets
