### ISSUE TITLE
Make the primary colour choice consistent

### ISSUE THREAD

**Issue by Benjamin-Piper** [UOA-SE701-Group3-2021/3Lancers#142]
**Describe the bug**
The colour choice for the designed widget icons, top-bar etc are inconsistent. **Please reply to this thread with the chosen primary colour.**

**To Reproduce**
View the figmas from the Design page of the Wiki

**Expected behavior**
The colours look different.

**Screenshots**

- ![image](https://user-images.githubusercontent.com/68324342/111854354-b11b2780-8983-11eb-8602-897bde4eb250.png)
- Above is #7A00F4
- ![image](https://user-images.githubusercontent.com/68324342/111854378-d60f9a80-8983-11eb-93fe-a4742c01cd3f.png)
- ![image](https://user-images.githubusercontent.com/68324342/111854467-4e765b80-8984-11eb-9760-d96c8bd8bb49.png)
- 2 Above are #6200EE
- ![image](https://user-images.githubusercontent.com/68324342/111854401-fd666780-8983-11eb-945b-fc5b25e2aeb7.png)
- Above is #210043

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ODE-BOY** [comment]
Icon Colour: #210043
Primary Purple Colour: #7A00F4

**Comment by Benjamin-Piper** [comment]
@lhuijser and @Milk-Yan are you OK with this?

**Comment by JChamberlain28** [comment]
should the text box be tinted purple to be consistent with other widgets @Benjamin-Piper ?

**Comment by Benjamin-Piper** [comment]
Closing this for now.
