### ISSUE TITLE
Add text widget icon to the widget drawer

### ISSUE THREAD

**Issue by Benjamin-Piper** [UOA-SE701-Group3-2021/3Lancers#158]
**Is your feature request related to a problem? Please describe.**
As an end user, I want to be able to create text on my bullet journal via the widget drawer so that I can record my thoughts.

**Describe the solution you'd like**
A `WidgetText` component to be added as a `WidgetDrawer` child.

**Describe alternatives you've considered**
Not having it in the widget drawer. Would have to double-click on the journal to create text which is currently too complicated at the moment.

**Additional context**
I want to see this hi-fi widget icon on the widget drawer.

![image](https://user-images.githubusercontent.com/68324342/111865561-b05ab380-89cc-11eb-8e0e-035c521d60d1.png)

**Comment by ysway** [comment]
Nice flat design
