### ISSUE TITLE
Increase Functionality of Current Widgets

### ISSUE THREAD

**Issue by werer9** [UOA-SE701-Group3-2021/3Lancers#161]
**Is your feature request related to a problem? Please describe.**
The current widgets are very basic and don't include much functionality. 

**Describe the solution you'd like**
Add support for text formatting in Text widgets. Improve the functionality of the habit tracker, etc.,

**Describe alternatives you've considered**
N/A

**Additional context**
n/a

**Comment by milkyway404** [comment]
Closed as too generic and documented in other issues.
