### ISSUE TITLE
Typo in WidgetCalendar component name

### ISSUE THREAD

**Issue by RawiriHohepa** [UOA-SE701-Group3-2021/3Lancers#165]
**Describe the bug**
The name of the component in WidgetCalendar.jsx does not match the file name - instead it is called WidgetTodo

**To Reproduce**
1. Go to WidgetCalendar.jsx
2. See the component name is WidgetTodo

**Expected behavior**
The component name should be the same as the file name i.e. WidgetCalendar

**Screenshots**
<img width="479" alt="image" src="https://user-images.githubusercontent.com/54158903/111867950-2e728680-89dc-11eb-9ecc-701e1213e17e.png">

**Comment by 96RadhikaJadhav** [comment]
@RawiriHohepa Can I work on it?
