### ISSUE TITLE
Publish Meeting Minutes to the GitHub Wiki

### ISSUE THREAD

**Issue by Benjamin-Piper** [UOA-SE701-Group3-2021/3Lancers#17]
**Is your feature request related to a problem? Please describe.**
As a contributor to this repository, I want to read the Meeting Minutes on the GitHub Wiki, so that I am aware of what is expected of me.

**Describe the solution you'd like**
A GitHub Wiki page of the Meeting Minutes. It should also be easily accessible from the Wiki sidebar.

**Describe alternatives you've considered**
Storing it on Google Drive - this would result in needless navigation away from GitHub.

**Additional context**
None.

**Comment by RawiriHohepa** [comment]
@Benjamin-Piper Can we separate the meeting minutes into different pages - one meeting per page? We could organise them in a similar way that they are on Google Drive.

**Comment by Benjamin-Piper** [comment]
That'll be a lot of pages 😅. What about having a page for each kind of meeting?

- Overarching
- Design 
- Frontend
- Backend
- FrontendxBackend
- FrontendxDesign

Plus any I've missed out on.

**Comment by RawiriHohepa** [comment]
That sounds good, the base meeting minutes page can just have links to each of those pages

**Comment by milkyway404** [comment]
Ben has done great work that has been recorded in the wiki!
