### ISSUE TITLE
Ability to add the weather to the Journal

### ISSUE THREAD

**Issue by AngelaLH** [UOA-SE701-Group3-2021/3Lancers#174]
**Is your feature request related to a problem? Please describe.**
As an end-user, I would like to be able to see the weather in the app to help me with planning my day around the weather

**Describe the solution you'd like**
The ability to have the option to put the weather into the Daily Journal that is tailored to my location, with a visual showing if the weather is rainy, cloudy, or sunny etc and the temperature of the day

**Describe alternatives you've considered**
Considered having a separate view you have to click into to see the weather, however, this makes it harder to see when you are planning your day and there will not be a record of what the weather was that day in the journal. Also considered including weather in the journal at all times, but the weather will not always be used or relevant in the journal.

**Additional context**
What the weather could look like in the Journal text view:
![image](https://user-images.githubusercontent.com/41172492/111888246-b178f880-8a3f-11eb-970e-53b0ec77ea69.png)

**Comment by Jaysce** [comment]
Fixed
