### ISSUE TITLE
Undesired warnings messages of frontend codes

### ISSUE THREAD

**Issue by ysway** [UOA-SE701-Group3-2021/3Lancers#189]
**Describe the bug**
When running the frontend app, there are many linter warning messages in the terminal, and there are warnings of unchanged files in the *GitHub Actions / Run Frontend Tests and Linter* as well

**To Reproduce**
`npm start`
Run GitHub Actions Tester

**Expected behaviour**
clean and no warnings and no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/20151850/111905249-875f1f00-8aaf-11eb-8906-7806c232e3fd.png)

**Comment by JChamberlain28** [comment]
Please note that a maximum of one person should be assigned to an issue unless it is complex and documentation on the fact 2 people are working on it is provided. 

This issue does not require more than one person, so I removed some assignments.
