### ISSUE TITLE
Implement API endpoint for the Dashboard view

### ISSUE THREAD

**Issue by flexzy** [UOA-SE701-Group3-2021/3Lancers#190]
**Is your feature request related to a problem? Please describe.**
As a front end developer, I want the API endpoints needed for the Dashboard view to be implemented, so I can interact with the back end and populate the dashboard with all the data for that widget.

**Describe the solution you'd like**
Implement the API endpoints needed for the dashboard endpoint, as discussed with frontend team

**Describe alternatives you've considered**
N/A

**Additional context**
Requirements had changed from original design/intention of the API, so this was not with the initial set of issues, but was established via drafting out the API endpoints (that is #95)

**Comment by khal745** [comment]
Future work: Implement much like how it returns in the `/api/journal` endpoint. It likely needs to return the entire month worth of data for the selected data eg. returning all the calendar events that occur in the month of March. Would likely require setting up a query with `$gte` and `$lte` for the given month.

**Comment by BlinkCreator** [comment]
Done
