### ISSUE TITLE
Combine delete endpoints for text widget

### ISSUE THREAD

**Issue by flexzy** [UOA-SE701-Group3-2021/3Lancers#191]
**Is your feature request related to a problem? Please describe.**
Currently, there are two endpoints for deleting text widget information. One from the journal API and the other from the text API. This results in the frontend needing to call two different API endpoints to delete one text widget instance.

**Describe the solution you'd like**
Move code from text API delete action to journal delete action.

**Describe alternatives you've considered**
Let front end call two endpoints - extra effort and is prone to bugs

**Comment by BlinkCreator** [comment]
Reviewed and looks like it is no longer an issue

**Comment by BlinkCreator** [comment]
@Jaysce
