### ISSUE TITLE
Missing unique keys for lists in DraggableWidget.jsx and JournalHabitTracker.jsx

### ISSUE THREAD

**Issue by JChamberlain28** [UOA-SE701-Group3-2021/3Lancers#199]
**Describe the bug**
A react warning regarding a lack of unique keys on list items is produced when running the GitHub CI tests.

**To Reproduce**
1. Make a PR
2. Let the tests run
3. See that the following errors occurs:

```
Warning: Each child in a list should have a unique "key" prop.
      
      Check the render method of Page. See https://reactjs.org/link/warning-keys for more information.
          at /home/runner/work/3Lancers/3Lancers/telos-frontend/src/dnd/DraggableWidget.jsx:20:11
```
and

```
 Warning: Each child in a list should have a unique "key" prop.
      
      Check the render method of `JournalHabitTracker`.
```
**Expected behavior**
No warning message for missing keys should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/51986824/112078262-f4bf9c80-8be2-11eb-83cf-62f8d9197e2a.png)

**Desktop (please complete the following information):**
 - OS: Linux (Github CI)
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
As these are warnings, they are not a high priority, however, do need attention.

**Comment by milkyway404** [comment]
Note Habit Tracker has been solved by PR #221
