### ISSUE TITLE
Adjust size of Journal Calendar to see pop up window

### ISSUE THREAD

**Issue by maheknangia** [UOA-SE701-Group3-2021/3Lancers#234]
**Describe the bug**
The adding menu doesn't show up fully when wanting to add, edit or delete an event in the Journal Calendar

**To Reproduce**
1. Go to the home screen of the Journal
2. Add a calendar widget
3. Double tap on a specific time 
4. See part of the adding menu

**Expected behavior**
The menu should be fully visible in the widget

**Screenshots**
![Screen Shot 2021-03-24 at 11 32 02 PM](https://user-images.githubusercontent.com/63040474/112295951-49553b80-8cf9-11eb-9e0d-e34f99984155.png)

**Comment by Jaysce** [comment]
Fixed
