### ISSUE TITLE
Backend tests are failing

### ISSUE THREAD

**Issue by JChamberlain28** [UOA-SE701-Group3-2021/3Lancers#236]
**Describe the bug**
Backend tests currently fail.

**To Reproduce**
Navigate to /telos-backend and run `npm test`.
This launches Jest and runs the backend tests.

**Expected behavior**
All tests pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/51986824/112296590-ee701400-8cf9-11eb-8ff0-ddebf72bc578.png)
![image](https://user-images.githubusercontent.com/51986824/112296659-f29c3180-8cf9-11eb-8894-1f175651da77.png)
![image](https://user-images.githubusercontent.com/51986824/112296699-f4fe8b80-8cf9-11eb-948e-b59624b5fe46.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser N/A
 - Version: N/A

**Additional context**
N/A

**Comment by milkyway404** [comment]
Issue not replicable. Most likely a dependency issue from error when setting up.
