### ISSUE TITLE
Weather Widget is draggable from below the widget

### ISSUE THREAD

**Issue by Alxjlv** [UOA-SE701-Group3-2021/3Lancers#286]
**Describe the bug**
The widget can be dragged from below where the item is seen on the screen

**To Reproduce**
1. Go to the journal view
2. Click on the weather widget icon
3. Click and drag about a centimeter below the widget

**Expected behavior**
Click and drag only working on the widget element

**Screenshots**
![image](https://user-images.githubusercontent.com/44216323/114300224-450b8980-9b13-11eb-8a21-838757d04ce9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Running in WSL

**Comment by BlinkCreator** [comment]
Already implemented by Sassindu
