### ISSUE TITLE
Define/Implement Schema for TodoList

### ISSUE THREAD

**Issue by werer9** [UOA-SE701-Group3-2021/3Lancers#30]
**Is your feature request related to a problem? Please describe.**
Yes, there needs to be a data structure for storing TodoList data.

**Describe the solution you'd like**
We will define a schema to be implemented in MongoDB

**Describe alternatives you've considered**
We could use a CSV file to implement this, however, this is not a very professional or secure way to store this data.

**Comment by flexzy** [comment]
This issue is now tracked in #123
