### ISSUE TITLE
Define/implement schema for Calendar

### ISSUE THREAD

**Issue by werer9** [UOA-SE701-Group3-2021/3Lancers#32]
**Is your feature request related to a problem? Please describe.**
Yes, the calendar widget does not currently store any data.

**Describe the solution you'd like**
I will define a schema in mongoDB that can be used to store the data used in the calendar widget.

**Describe alternatives you've considered**
We could use local CSV files however, this is not industry standard.

**Comment by flexzy** [comment]
This issue is now tracked in #123
