### ISSUE TITLE
Define/implement HabitTracker widget schema

### ISSUE THREAD

**Issue by werer9** [UOA-SE701-Group3-2021/3Lancers#33]
**Is your feature request related to a problem? Please describe.**
Yes, the HabitTracker widget does not currently store any data.

**Describe the solution you'd like**
We will define a schema in mongoDB that can be used to store the data used in the HabitTracker widget.

**Describe alternatives you've considered**
We could use local CSV files however, this is not industry standard.

**Comment by flexzy** [comment]
This issue is now tracked in #123
