### ISSUE TITLE
Habit tracker (Journal / Daily View) - Design

### ISSUE THREAD

**Issue by ysway** [UOA-SE701-Group3-2021/3Lancers#52]
**Is your feature request related to a problem? Please describe.**
There is an implementation of the design of the habit tracker "widget" for the journal / daily view.

**Describe the solution you'd like**
Create a react component that implements the design of the habit tracker in the journal / daily view. 

**Describe alternatives you've considered**
*N/A*

**Additional context**
This will be a design that is for demonstration only, with no functionality.

**Comment by RawiriHohepa** [comment]
This needs a good description of the feature before it can be approved

**Comment by ysway** [comment]
> This needs a good description of the feature before it can be approved

Didn't notice that the description was the same as the template. I might forget to update the comment before I closed the tab. Thanks for informing me.
