### ISSUE TITLE
Habit tracker (Journal / Daily View) - Functionality w/ dummy data

### ISSUE THREAD

**Issue by ysway** [UOA-SE701-Group3-2021/3Lancers#55]
**Is your feature request related to a problem? Please describe.**
The tracker has no ability to track the actions or events as it only displays fixed content, needs a function that can read data from the (dummy) database so the tracker can displays the events and actions dynamically.

**Describe the solution you'd like**
Using dummy data for the widget to be functional and ensure that the widget can read and display correctly.

**Describe alternatives you've considered**
Implement the function with data structure agreed in advance but without testing with dummy data, but that would be dangerous as which may require more effort to debug in final stage and cause schedule slip.

**Comment by lhuijser** [comment]
The first description is a little bit vague, could you please use a user story (similar to other approved issues) to describe, or clarify the one you have written? Looks great other than this :)

**Comment by ysway** [comment]
> The first description is a little bit vague, could you please use a user story (similar to other approved issues) to describe, or clarify the one you have written? Looks great other than this :)

Updated
