### ISSUE TITLE
Daily Journal - Implement Design Prototype

### ISSUE THREAD

**Issue by RawiriHohepa** [UOA-SE701-Group3-2021/3Lancers#61]
**Is your feature request related to a problem? Please describe.**
As a frontend developer, I want a barebones implementation of the design for the Daily Journal so that I can begin implementing the functionality.

**Describe the solution you'd like**
A react frontend implementation of the prototype design for the Daily Journal. No functionality is required beyond what is required to fully implement the prototype design.

**Describe alternatives you've considered**
The design could be implemented at the same time as the functionality, but this would increase the size of the resulting PR and would be more difficult to test.

**Additional context**
Blocked by #48

**Comment by Benjamin-Piper** [comment]
Here's the [journal](https://github.com/UOA-SE701-Group3-2021/3Lancers/files/6145878/journal.svg.zip.zip). Uploaded as a `zip` because GitHub doesn't support SVG upload here.

**Comment by Benjamin-Piper** [comment]
Here's the 
![journal](https://user-images.githubusercontent.com/68324342/111406755-b5530500-8737-11eb-904d-55dc9c032ad6.png) as a PNG (instead of SVG).
