### ISSUE TITLE
Daily Journal - Implement Functionality to Change Current Day

### ISSUE THREAD

**Issue by RawiriHohepa** [UOA-SE701-Group3-2021/3Lancers#64]
**Is your feature request related to a problem? Please describe.**
As an end user I want to be able to change the current day of the Daily Journal so that I can choose what day to use the Daily Journal for.

**Describe the solution you'd like**
Implemented functionality of being able to change the current day on the Daily Journal page. The user can go to the next or previous day, or choose a specific date to change to. Any necessary data may be stored locally in state - no connection to the backend API is necessary.

**Describe alternatives you've considered**
Don't implement this functionality, which would remove a core feature of the product i.e. being able to use the Daily Journal for multiple days.

**Additional context**
Blocked by #61

**Comment by RawiriHohepa** [comment]
@lhuijser I assume you approve of the issue since you've picked it up - can you add the approved label?

**Comment by lhuijser** [comment]
> @lhuijser I assume you approve of the issue since you've picked it up - can you add the approved label?

Yes, apologies! Slipped my mind sorry, will do now :)
