### ISSUE TITLE
Daily Journal - Implement Functionality to Add and Remove Widgets

### ISSUE THREAD

**Issue by RawiriHohepa** [UOA-SE701-Group3-2021/3Lancers#65]
Is your feature request related to a problem? Please describe.
As an end user I want to be able to add and remove widgets from each day of the Daily Journal so that I can customise each day of my Daily Journal with the widgets that I want.

Describe the solution you'd like
Implemented functionality of being able to drag new widgets onto the Daily Journal page, drag widgets around to reposition on the Daily Journal page, and drag to remove widgets from the Daily Journal page. Each day in the Daily Journal should be able to have different widgets on them. Any necessary data may be stored locally in state - no connection to the backend API is necessary.

Describe alternatives you've considered
Don't implement this functionality, which would remove a core feature of the product i.e. being able to customise widgets on the Daily Journal page.

Additional context
Blocked by #61

**Comment by ambiyu** [comment]
Adding widgets to the journal via the widget drawer (without drag and drop) has been implemented in PR #198.
Functionality for removing widgets still needs to be implemented.

**Comment by a-158w** [comment]
This issue has been broken down into two smaller issues #238 and #135  and this will now be closed.
