### ISSUE TITLE
Setup Linting and Prettier using Airbnb style for frontend

### ISSUE THREAD

**Issue by ambiyu** [UOA-SE701-Group3-2021/3Lancers#67]
**Is your feature request related to a problem? Please describe.**
We should have consistent formatting and code style/guidelines across the codebase.

**Describe the solution you'd like**
Setup linting and prettier for the project so that we keep a consistent code style.

**Describe alternatives you've considered**
There are other code styles guides like Google, but the Airbnb style guide seems to be the most suitable for React.

**Additional context**
None

**Comment by RawiriHohepa** [comment]
@ambiyu make sure you assign yourself to issues when you begin working on them and move them to the appropriate part of the project board
