### ISSUE TITLE
Publish Contribution Guidelines to the GitHub Wiki

### ISSUE THREAD

**Issue by Benjamin-Piper** [UOA-SE701-Group3-2021/3Lancers#8]
**Is your feature request related to a problem? Please describe.**
As a contributor to this repository, I want to read the Contribution Guidelines on the GitHub Wiki, so that I am aware of what is expected of me.

**Describe the solution you'd like**
A GitHub Wiki page of the Contribution Guidelines. It should also be easily accessible from the Wiki sidebar.

**Describe alternatives you've considered**
Storing it on Google Drive - this would result in needless navigation away from GitHub.

**Additional context**
None.

**Comment by Benjamin-Piper** [comment]
Pending on #7 so that I can insert a link to the Code of Conduct article.

**Comment by a-158w** [comment]
> Pending on #7 so that I can insert a link to the Code of Conduct article.

Added

**Comment by Benjamin-Piper** [comment]
Thanks! All done now
