### ISSUE TITLE
Calendar (dashboard / fullscreen) - Implement design

### ISSUE THREAD

**Issue by hsingh124** [UOA-SE701-Group3-2021/3Lancers#80]
**Is your feature request related to a problem? Please describe.**
Currently there is no implementation of the calendar widget in dashboard/fullscreen view.

**Describe the solution you'd like**
I want there to be a react component for the implementation of the dashboard/fullscreen calendar widget. Only design, no functionality.

**Describe alternatives you've considered**
- Instead of a fullscreen calendar, add some sort of redirect to a calendar app like google calendar and integrate the user data with it.
- Use another calendar app that the user already uses as an iframe on the web-app.

**Additional context**
Currently thinking of using the below options:
- https://fullcalendar.io/
- https://www.npmjs.com/package/react-big-calendar
- https://www.npmjs.com/package/react-calendar

**Comment by a-158w** [comment]
> I want there

There needs

**Comment by milkyway404** [comment]
Not sure why this issue isn't closed, there was a pull request to close this issue that was merged already.
