### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by ambiyu** [UOA-SE701-Group3-2021/3Lancers#86]
**Is your feature request related to a problem? Please describe.**
We would like setup CI/CD to automate some of the development/PR workflow. 

**Describe the solution you'd like**
Setup GitHub actions to automatically test and run linter/prettier

**Describe alternatives you've considered**
None

**Additional context**
Need to add the lint script to the frontend so it can automatically run the linter when we make a PR.

**Comment by RawiriHohepa** [comment]
Can you include in the solution what the actions should do? E.g. Run lint script, run tests
