### ISSUE TITLE
Setup Frontend README

### ISSUE THREAD

**Issue by AngelaLH** [UOA-SE701-Group3-2021/3Lancers#89]
**Is your feature request related to a problem? Please describe.**
As a contributor to this repository, I want to read a README, so that I can have an understanding of how to run the app and what to install

**Describe the solution you'd like**
A README file that explains what to install and how to build and make changes to the app

**Describe alternatives you've considered**
No README, this would mean people using the repository wouldn't know what to install or how to start and build the app

**Additional context**
None.

**Comment by RawiriHohepa** [comment]
@AngelaLH could you change the solution and alternatives descriptions, they don't make sense for a readme that's stored in the code. Could you also change the location of the readme in the problem description? After that I'm happy to approve
