### ISSUE TITLE
Widget Drawer UI

### ISSUE THREAD

**Issue by a-158w** [UOA-SE701-Group3-2021/3Lancers#93]
**Is your feature request related to a problem? Please describe.**
I want a widget drawer that can hold widget icons.

**Describe the solution you'd like**
A side bar that can be shown or hidden on the left side of the screen with placeholder widget icons.

**Describe alternatives you've considered**
Having a double click menu to insert widgets however this is not as efficient as dragging from a drawer.

**Additional context**
#65 depends on this.

**Comment by RawiriHohepa** [comment]
This looks like a duplicate issue based on the solution description - see #65

**Comment by Benjamin-Piper** [comment]
I'll work on getting the sidebar component without drag-and-drop functionality. And I'll edit this issue to make it clearer.
